---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: canonical-ubuntu-12.04
  driver_config:
    box: canonical-ubuntu-12.04
    box_url: https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box
- name: ubuntu-12.04
- name: ubuntu-10.04
- name: debian-7.1.0
- name: centos-6.4
- name: centos-5.9
- name: scientific-6.0
  driver_config:
    box: lyte-scientific-6-minimal
    box_url: http://lyte.id.au/vagrant/sl6-64-lyte.box
- name: fedora-18
- name: fedora-20

suites:
- name: default
  run_list:
    - recipe[sysctl_test]
  attributes:
    sysctl:
      params:
        vm:
          swappiness: 19
        net:
          ipv4:
            tcp_fin_timeout: 29
- name: override_conf
  run_list:
    - recipe[sysctl_test]
  attributes:
    sysctl:
      allow_sysctl_conf: true
      params:
        vm:
          swappiness: 19
        net:
          ipv4:
            tcp_fin_timeout: 29
